---
title: 19-21 Website
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  tenants:
    title: Tenants
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: tenants
  values:
    website: ''
    column: ''
    metadesc: ''
permalink: pretty
exclude:
- Gemfile.lock
- Gemfile
- README*
- node_modules
- ".gitignore"
- assets/scripts/src
- yarn.lock
- ".git"
sass:
  sass_dir: assets/styles/
  style: compressed
